### ISSUE TITLE
Error in the first indexing pass of a batch of data

### ISSUE THREAD

**Issue by bzg** [juji-io/datalevin#177]
Using [this test script](https://github.com/bzg/test-dtlv-load/blob/main/test2.clj) with dtlv 0.8.0 (as a babashka pod), I get this error:

```
#error {                        
 :cause Document does not exist.                                                   
 :data {:doc-ref #datalevin/Datom [24 :description Arago is a software package designed for the astrometric measurement of natural satellite positions in images taken 
using                             
the Imaging Science Subsystem (ISS) of the Cassini spacecraft.]}                                                                                                        :via       
 [{:type clojure.lang.ExceptionInfo                                                                                                                                    
   :message Document does not exist.
   :data {:doc-ref #datalevin/Datom [24 :description Arago is a software package designed for the astrometric measurement of natural satellite positions in images take
n using                                                                            
the Imaging Science Subsystem (ISS) of the Cassini spacecraft.]}
   :at [datalevin.search.SearchEngine remove_doc search.clj 347]}]
 :trace
 [[datalevin.search.SearchEngine remove_doc search.clj 347]       
  [datalevin.storage.Store load_datoms storage.cljc 367]
  [datalevin.db$local_transact_tx_data invokeStatic db.cljc 1223]
  [datalevin.db$transact_tx_data invokeStatic db.cljc 1258]                     
  [datalevin.core$with invokeStatic core.cljc 376]
  [datalevin.core$with invoke core.cljc 370]     
  [datalevin.core$with invokeStatic core.cljc 373]                                                                                                                     
  [datalevin.core$_transact_BANG_$fn__13483$fn__13488 invoke core.cljc 630]
  [datalevin.core$_transact_BANG_$fn__13483 invoke core.cljc 629]
  [datalevin.core$_transact_BANG_ invokeStatic core.cljc 629]
  [datalevin.core$transact_BANG_ invokeStatic core.cljc 634]
  [pod.huahaiy.datalevin$transact_BANG_$fn__21252 invoke datalevin.clj 217]
  [pod.huahaiy.datalevin$transact_BANG_ invokeStatic datalevin.clj 217]
  [pod.huahaiy.datalevin$transact_BANG_ invoke datalevin.clj 212]
  [pod.huahaiy.datalevin$transact_BANG_ invokeStatic datalevin.clj 214]
  [pod.huahaiy.datalevin$transact_BANG_ invoke datalevin.clj 212]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144] 
  [clojure.core$apply invokeStatic core.clj 667]
  [pod.huahaiy.datalevin$run$fn__21376 invoke datalevin.clj 583]
  [pod.huahaiy.datalevin$run invokeStatic datalevin.clj 575]
  [datalevin.main$_main invokeStatic main.clj 590]
  [datalevin.main$_main doInvoke main.clj 576]
  [clojure.lang.RestFn invoke RestFn.java 397]
  [clojure.lang.AFn applyToHelper AFn.java 152]
  [clojure.lang.RestFn applyTo RestFn.java 132]
  [datalevin.main main nil -1]]}
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Document does not exist.
Data:     {:doc-ref #object[com.cognitect.transit.impl.TaggedValueImpl 0x25b47473 "com.cognitect.transit.impl.TaggedValueImpl@d363529a"], :type "class clojure.lang.Exc
eptionInfo"}
Location: /home/xxx/.../test-cdg-load/./test.clj:18:1

----- Context ------------------------------------------------------------------
14:                            :db/fulltext  true}})
15: (def conn (d/get-conn "/tmp/test-dtlv" schema))
16: (def db (d/db conn))
17: 
18: (d/transact! conn (json/parse-string (slurp "all.json") true))
    ^--- Document does not exist.

----- Stack trace --------------------------------------------------------------
babashka.pods.impl/processor         - <built-in>
babashka.pods.sci/load-pod/fn--27048 - <built-in>
user                                 - /home/bzg/Documents/boulot/etalab/git/code.gouv.fr/etalab-cli-tools/test-cdg-load/./test.clj:18:1
```

Not _always_ though: when I get this error while indexing a small set of entries, say 100, re-running the script results in no error... but then, testing with a larger set of entries, the errors reappears and for good.

Can I help debugging this further?

**Comment by huahaiy** [comment]
You can help by running Datalevin as a Clojure library. Looks to be a transit encoding problem with some strings.

**Comment by huahaiy** [comment]
Reproduced. Will have a fix soon.

**Comment by huahaiy** [comment]
Fixed in 0.8.2

**Comment by bzg** [comment]
The test repo contains the data in the `all.json` file, so that you can reproduce the problem.

The problem persists for me with 0.8.1, with random `Document does not exists` errors, similar to the one I reported. 

Sure, I will try using Datalevin as a Clojure library, but I was hoping I could use it as a babashka pod because I'm experimenting with a cli tool to interact with a local db.  I'll see if I can build the cli tool without babashka.

**Comment by huahaiy** [comment]
"Document does not exists" error should be fixed. That is, if you switch to a fresh DB directory. Don't use the old one, the format are different.

There are other problem with this data set, so I couldn't load it either. That json file contains descriptions in other language (French?) that the default english analyzer seems to have trouble with. Basically, the data encoding is throwing off nippy encoder:

clojure.lang.ExceptionInfo: Fail to transact to LMDB: #error {
 :cause "Error putting r/w key buffer of \"datalevin/docs\"with value[97 :description \"GraphstatsR est une application permettant le l'analyses de données de quantification métabolomiques prétraitées (MS, RMN). Elle permet la génération d'analyse descriptive (ACP), de représentations graphiques type boxplot avec tests statistiques associées, cela avec une interactivité permettant à l'utilisateur d'ajuster au mieux les analyses. Cette application peut traiter des données issues d'autres méthodes à condition de fournir des fichiers d'entrée au bon format.  \\r\\nhttps://graphstatsr.sk8.inrae.fr\"]: nil"
 :data {:type :data}

**Comment by bzg** [comment]
> "Document does not exists" error should be fixed. 

I still have one: I updated the script and bisected until I've a reproducible error, see the comments in the code. I can see nothing wrong with the json entry that makes the indexing choke, do you?

The `Error putting r/w key buffer of "datalevin/docs"` are gone.

Thanks for your patience in trying to sort this out!

**Comment by huahaiy** [comment]
Thank you for dissecting this problem. I believe I have found the cause. The `:id` field is marked as `unique` in the schema, but the `:id` in the data is not, so we had to delete existing entities.  So this data set gives me a lot of cases that simulates a lot of transaction situations. This particular error, is due to this case: the original `:description` is huge, but the new one is small, which is a case I did not thought of. A fix is coming.

**Comment by bzg** [comment]
Great, I'm glad bisecting helped, thanks again!

**Comment by huahaiy** [comment]
0.8.4 fixes this.

**Comment by theronic** [comment]
I am using Datalevin v0.9.8 with Electric Clojure and am encountering the same "Document does not exist" exception for entities that were transacted before I added `:db/unique :db.unique/identity` & `:db/fulltext true` to the `:term/text` attribute. Entities added after the schema change, do not trigger the exception.

When I transact `[:db/retractEntity id]`, the entity is suscessfully deleted, but a query or pull fails on the Electric view side, possibly a destructure of Datalevin entity.

[Debugging discussion here](https://clojurians.slack.com/archives/C7Q9GSHFV/p1721812581430589) on Clojurians.

**Comment by huahaiy** [comment]
This exception should be unrelated. 

Please try master branch to see if this is fixed. Basically, now we commit fulltext index before commit datoms.
