### ISSUE TITLE
Mixed variables in complex queries

### ISSUE THREAD

**Issue by ribelo** [juji-io/datalevin#8]
If the number of assigned variables in the query is greater than 8, everything becomes mixed up. Probably guilty is the ``zipmap`` used somewhere in the code, which only keeps the order when the number of keys <=8. Bug does not exist in datascript

```clojure
(require '[taoensso.encore :as e])

(let [data (->> (range 1000)
                (map (fn [i] {:a (e/uuid-str)
                              :b (e/uuid-str)
                              :c (e/uuid-str)
                              :d (e/uuid-str)
                              :e (rand-int 3)
                              :f (rand-int 3)
                              :g (rand-int 3)
                              :h (rand-int 3)})))
      conn (d/create-conn {:a {:db/valueType :db.type/string}
                           :b {:db/valueType :db.type/string}
                           :c {:db/valueType :db.type/string}
                           :d {:db/valueType :db.type/string}
                           :e {:db/valueType :db.type/double}
                           :f {:db/valueType :db.type/double}
                           :g {:db/valueType :db.type/double}
                           :h {:db/valueType :db.type/double}})
      db    (-> (d/empty-db)
                (d/db-with data))]
  (d/q '[:find     ?eid1 .
         :where
         [?eid1 :a ?a1]
         [?eid1 :b ?b1]
         [?eid1 :c ?c1]
         [?eid1 :d ?d1]
         [?eid1 :e ?e1]
         [?eid1 :f ?f1]
         [?eid1 :g ?g1]
         [?eid1 :h ?h1]
         [?eid2 :e ?e1]]
    db))
;; => "efff5a2a-6ee0-49fa-bd4e-7f5cc3a8bc4c"
```
Instead of `eid`, a random variable is returned.

**Comment by huahaiy** [comment]
Thanks, this is fixed in datascript recently. Now incorporated in 0.2.10.

**Comment by ribelo** [comment]
Unfortunately, it still doesn't work. I suggest you add a test to cover that. Thanks for your work, by the way.

**Comment by huahaiy** [comment]
Haha, late night..., forgot to put in `(is ...)` in the test, so didn't catch the error. Released 0.2.11 to fix it.
